[package]
name = "birdlgd"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
thiserror = "1"
regex = "1"
chrono = { version = "0", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_cbor = "0"
serde_json = "1"
lazy_static = "1.4.0"
